# Generated by Django 3.1.4 on 2022-03-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_settings', '0004_sitesetting_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='logo',
            new_name='logo_image',
        ),
    ]
